[pytest]
testpaths = tests
pythonpath = .
log_cli = true
log_cli_level = INFO
log_file = reports/ejecucion.log
log_file_level = INFO
log_file_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
